[program:honeypot]
command=/home/ubuntu/AI-Driven-Honeypot-with-Attacker-Profiling/honeypot/.venv/bin/python main.py
directory=/home/ubuntu/AI-Driven-Honeypot-with-Attacker-Profiling
user=ubuntu
autostart=true
autorestart=true
startretries=5
startsecs=3
stdout_logfile=/var/log/honeypot.log
stderr_logfile=/var/log/honeypot.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=3
environment=HOME="/home/ubuntu",USER="ubuntu"

[program:dashboard]
command=/home/ubuntu/AI-Driven-Honeypot-with-Attacker-Profiling/honeypot/.venv/bin/python honeypot/dashboard/app.py
directory=/home/ubuntu/AI-Driven-Honeypot-with-Attacker-Profiling
user=ubuntu
autostart=true
autorestart=true
startretries=5
startsecs=3
stdout_logfile=/var/log/dashboard.log
stderr_logfile=/var/log/dashboard.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=3
environment=HOME="/home/ubuntu",USER="ubuntu"